# Generated by Django 5.2.5 on 2026-06-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('results_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WSISample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=255)),
                ('x_wsi', models.IntegerField()),
                ('y_wsi', models.IntegerField()),
                ('x_thumb', models.FloatField()),
                ('y_thumb', models.FloatField()),
                ('crop_size', models.IntegerField(default=128)),
                ('nuc_count', models.IntegerField(default=0)),
                ('focus_score', models.FloatField(default=0.0)),
                ('edge_density', models.FloatField(default=0.0)),
                ('cyto_frac', models.FloatField(default=0.0)),
                ('candidate_type', models.CharField(choices=[('single_cell', 'Célula Individual'), ('cell_cluster', 'Agrupación Celular'), ('low_quality', 'Baja Calidad'), ('artifact_like', 'Artefacto'), ('uncertain_candidate', 'Candidato Dudoso')], max_length=50)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='wsi_analysis.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_type', models.CharField(max_length=50)),
                ('image_path', models.CharField(max_length=1024)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='wsi_analysis.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pred_label', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('probabilities', models.JSONField(default=dict)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='wsi_analysis.candidatecell')),
            ],
        ),
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_id', models.CharField(max_length=50)),
                ('x1_thumb', models.IntegerField()),
                ('y1_thumb', models.IntegerField()),
                ('x2_thumb', models.IntegerField()),
                ('y2_thumb', models.IntegerField()),
                ('x1_wsi', models.IntegerField()),
                ('y1_wsi', models.IntegerField()),
                ('x2_wsi', models.IntegerField()),
                ('y2_wsi', models.IntegerField()),
                ('n_candidates', models.IntegerField(default=0)),
                ('n_abnormal', models.IntegerField(default=0)),
                ('priority_score', models.FloatField(default=0.0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='wsi_analysis.analysisrun')),
            ],
        ),
        migrations.AddField(
            model_name='candidatecell',
            name='roi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='wsi_analysis.roi'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='wsi_analysis.wsisample'),
        ),
    ]
