# Generated by Django 5.2.5 on 2026-07-06 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsi_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecell',
            name='x_slide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatecell',
            name='y_slide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_id', models.CharField(max_length=50)),
                ('x1_wsi', models.IntegerField()),
                ('y1_wsi', models.IntegerField()),
                ('x2_wsi', models.IntegerField()),
                ('y2_wsi', models.IntegerField()),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='wsi_analysis.roi')),
            ],
        ),
        migrations.AddField(
            model_name='candidatecell',
            name='slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='wsi_analysis.slide'),
        ),
    ]
